org.gradle.jvmargs=-Xmx4G
org.gradle.caching=true
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.20
forge_version_range=[47,)
loader_version_range=[47,)
mod_id=masterblacksmith
mod_name=The Master Blacksmith
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.masterblacksmith
mod_authors=Dung
mod_description=True Metallurgy - a real blacksmithing profession for Minecraft. Ore, heat, hammer, quench, grind, assembly and craftsmanship.
